version: "3"

services:
  go-resume-svc-app:
      command: reflex -sr '\.go$|\.mod$' -- sh -c "go run cmd/main.go"
      build:
        dockerfile: Dockerfile.local
        context: .
      depends_on:
        - go-resume-svc-redis
      environment:
        - HTTP_SERVER_PORT=38983
        - CACHE_HOST=go-resume-svc-redis
        - CACHE_PORT=6379
        - SERVICE_NAME=go-resume-svc
        - ENVRIONMENT=local
      volumes:
        - .:/go/src/app
      working_dir: /go/src/app
      ports:
        - "38983:38983"
  go-resume-svc-redis:
    image: redis:latest
    ports:
      - "6379:6379"