version: "3"

services:
  go-resume-svc-app:
      command: reflex -sr '\.go$|\.mod$' -- sh -c "go run cmd/main.go"
      build:
        dockerfile: Dockerfile.local
        context: .
      environment:
        - HTTP_SERVER_PORT=3003
        - SERVICE_NAME=go-resume-svc
        - ENVRIONMENT=local
      volumes:
        - .:/go/src/app
      working_dir: /go/src/app
      ports:
        - "3003:3003"